# Modules:
# - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
---
- name: === UNSUPPORTED OS FAMILY ===
  block:
  - debug:
      msg: "{{ansible_os_family}} is not supported"
  - meta: end_play
  when:
  - ansible_os_family|lower != 'debian'
  - ansible_os_family|lower != 'redhat'
  - not force_install|default(false)

- name: Install
  include_tasks: "_install.yml"
  when: cni['install']
...
